//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string CompanyStatus { get; set; }
        public string CompanyCode { get; set; }
        public string PayrollStatus { get; set; }
        public string PayrollCode { get; set; }
    }
}
